export const bamboo = [ // 竹子数据
  {
    type: '毛竹',
    bambooData: [{
      area:'奉化区',name:'合计种植总面积',value:'259060',unit:'亩'
    },{
      area:'奉化区',name:'合计总珠数',value:'746027',unit:'个'
    },{
      area:'奉化区',name:'合计壯龄竹珠数',value:'562361',unit:'个'
    },{
      area:'奉化区',name:'合计老龄竹珠数',value:'183666',unit:'个'
    },{
      area:'奉化区',name:'合计防护林种植总面积',value:'134266',unit:'亩'			
    },{
      area:'奉化区',name:'合计防护林总珠数',value:'399721',unit:'个'
    },{
      area:'奉化区',name:'合计防护林壯龄竹珠数',value:'362537',unit:'个'
    },{
      area:'奉化区',name:'合计防护林老龄竹珠数',value:'37183',unit:'个'
    },{
      area:'奉化区',name:'合计特用林种植总面积',value:'94',unit:'亩'			
    },{			
      area:'奉化区',name:'合计特用林总珠数',value:'318',unit:'个'
    },{
      area:'奉化区',name:'合计特用林壯龄竹珠数',value:'195',unit:'个'
    },{
      area:'奉化区',name:'合计特用林老龄竹珠数',value:'123',unit:'个'
    },{
      area:'奉化区',name:'合计用材林种植总面积',value:'124700',unit:'亩'						
    },{			
      area:'奉化区',name:'合计用材林总珠数',value:'345988',unit:'个'
    },{
      area:'奉化区',name:'合计用材林壯龄竹珠数',value:'199628',unit:'个'
    },{
      area:'奉化区',name:'合计用材林老龄竹珠数',value:'146360',unit:'个'
    },{
      area:'奉化区',name:'人工种植总面积',value:'253482',unit:'亩'
    },{
      area:'奉化区',name:'人工总珠数',value:'729846',unit:'个'		
    },{
      area:'奉化区',name:'人工壯龄竹珠数',value:'546782',unit:'个'
    },{
      area:'奉化区',name:'人工老龄竹珠数',value:'183065',unit:'个'
    },{
      area:'奉化区',name:'人工防护林种植总面积',value:'132707',unit:'亩'						
    },{
      area:'奉化区',name:'人工防护林总珠数',value:'394643',unit:'个'
    },{
      area:'奉化区',name:'人工防护林壯龄竹珠数',value:'357984',unit:'个'
    },{
      area:'奉化区',name:'人工防护林老龄竹珠数',value:'36660',unit:'个'
    },{
      area:'奉化区',name:'人工特用林种植总面积',value:'66',unit:'亩'						
    },{			
      area:'奉化区',name:'人工特用林总珠数',value:'220',unit:'个'
    },{
      area:'奉化区',name:'人工特用林壯龄竹珠数',value:'97',unit:'个'
    },{
      area:'奉化区',name:'人工特用林老龄竹珠数',value:'123',unit:'个'
    },{
      area:'奉化区',name:'人工用材林种植总面积',value:'120709',unit:'亩'						
    },{			
      area:'奉化区',name:'人工用材林总珠数',value:'334984',unit:'个'
    },{
      area:'奉化区',name:'人工用材林壯龄竹珠数',value:'188701',unit:'个'
    },{
      area:'奉化区',name:'人工用材林老龄竹珠数',value:'146282',unit:'个'
    },{			
      area:'奉化区',name:'天然种植总面积',value:'5578',unit:'亩'
    },{
      area:'奉化区',name:'天然总珠数',value:'16181',unit:'个'		
    },{
      area:'奉化区',name:'天然壯龄竹珠数',value:'15579',unit:'个'
    },{
      area:'奉化区',name:'天然老龄竹珠数',value:'601',unit:'个'
    },{
      area:'奉化区',name:'天然防护林种植总面积',value:'1559',unit:'亩'						
    },{
      area:'奉化区',name:'天然防护林总珠数',value:'5078',unit:'个'
    },{
      area:'奉化区',name:'天然防护林壯龄竹珠数',value:'4554',unit:'个'
    },{
      area:'奉化区',name:'天然防护林老龄竹珠数',value:'524',unit:'个'
    },{
      area:'奉化区',name:'天然特用林种植总面积',value:'28',unit:'亩'						
    },{			
      area:'奉化区',name:'天然特用林总珠数',value:'98',unit:'个'
    },{
      area:'奉化区',name:'天然特用林壯龄竹珠数',value:'98',unit:'个'
    },{
      area:'奉化区',name:'天然特用林老龄竹珠数',value:'0',unit:'个'
    },{
      area:'奉化区',name:'天然用材林种植总面积',value:'3991',unit:'亩'						
    },{			
      area:'奉化区',name:'天然用材林总珠数',value:'11005',unit:'个'
    },{
      area:'奉化区',name:'天然用材林壯龄竹珠数',value:'10927',unit:'个'
    },{
      area:'奉化区',name:'天然用材林老龄竹珠数',value:'78',unit:'个'
    },{
      area:'锦屏街道',name:'合计种植总面积',value:'6312',unit:'亩'			
    },{
      area:'锦屏街道',name:'合计总珠数',value:'20349',unit:'个'
    },{
      area:'锦屏街道',name:'合计壯龄竹珠数',value:'17346',unit:'个'
    },{
      area:'锦屏街道',name:'合计老龄竹珠数',value:'3003',unit:'个'
    },{
      area:'锦屏街道',name:'合计防护林种植总面积',value:'0',unit:'亩'			
    },{
      area:'锦屏街道',name:'合计防护林总珠数',value:'0',unit:'个'
    },{
      area:'锦屏街道',name:'合计防护林壯龄竹珠数',value:'0',unit:'个'
    },{
      area:'锦屏街道',name:'合计防护林老龄竹珠数',value:'0',unit:'个'			
    },{
      area:'锦屏街道',name:'合计特用林种植总面积',value:'8',unit:'亩'			
    },{
      area:'锦屏街道',name:'合计特用林总珠数',value:'23',unit:'个'
    },{
      area:'锦屏街道',name:'合计特用林壯龄竹珠数',value:'23',unit:'个'
    },{
      area:'锦屏街道',name:'合计特用林老龄竹珠数',value:'0',unit:'个'						
    },{
      area:'锦屏街道',name:'合计用材林种植总面积',value:'6304',unit:'亩'						
    },{			
      area:'锦屏街道',name:'合计用材林总珠数',value:'20326',unit:'个'
    },{
      area:'锦屏街道',name:'合计用材林壯龄竹珠数',value:'17323',unit:'个'
    },{
      area:'锦屏街道',name:'合计用材林老龄竹珠数',value:'3003',unit:'个'
    },{
      area:'锦屏街道',name:'人工种植总面积',value:'6178',unit:'亩'			
    },{
      area:'锦屏街道',name:'人工总珠数',value:'19908',unit:'个'		
    },{
      area:'锦屏街道',name:'人工壯龄竹珠数',value:'16926',unit:'个'
    },{
      area:'锦屏街道',name:'人工老龄竹珠数',value:'2982',unit:'个'
    },{
      area:'锦屏街道',name:'人工防护林种植总面积',value:'0',unit:'亩'						
    },{
      area:'锦屏街道',name:'人工防护林总珠数',value:'0',unit:'个'
    },{
      area:'锦屏街道',name:'人工防护林壯龄竹珠数',value:'0',unit:'个'
    },{
      area:'锦屏街道',name:'人工防护林老龄竹珠数',value:'0',unit:'个'
    },{
      area:'锦屏街道',name:'人工特用林种植总面积',value:'8',unit:'亩'						
    },{			
      area:'锦屏街道',name:'人工特用林总珠数',value:'23',unit:'个'
    },{
      area:'锦屏街道',name:'人工特用林壯龄竹珠数',value:'23',unit:'个'
    },{
      area:'锦屏街道',name:'人工特用林老龄竹珠数',value:'0',unit:'个'
    },{
      area:'锦屏街道',name:'人工用材林种植总面积',value:'6170',unit:'亩'						
    },{			
      area:'锦屏街道',name:'人工用材林总珠数',value:'19885',unit:'个'
    },{
      area:'锦屏街道',name:'人工用材林壯龄竹珠数',value:'16903',unit:'个'
    },{
      area:'锦屏街道',name:'人工用材林老龄竹珠数',value:'2982',unit:'个'			
    },{			
      area:'锦屏街道',name:'天然种植总面积',value:'134',unit:'亩'
    },{
      area:'锦屏街道',name:'天然总珠数',value:'441',unit:'个'		
    },{
      area:'锦屏街道',name:'天然壯龄竹珠数',value:'420',unit:'个'
    },{
      area:'锦屏街道',name:'天然老龄竹珠数',value:'21',unit:'个'
    },{
      area:'锦屏街道',name:'天然防护林种植总面积',value:'0',unit:'亩'						
    },{
      area:'锦屏街道',name:'天然防护林总珠数',value:'0',unit:'个'
    },{
      area:'锦屏街道',name:'天然防护林壯龄竹珠数',value:'0',unit:'个'
    },{
      area:'锦屏街道',name:'天然防护林老龄竹珠数',value:'0',unit:'个'
    },{
      area:'锦屏街道',name:'天然特用林种植总面积',value:'0',unit:'亩'						
    },{			
      area:'锦屏街道',name:'天然特用林总珠数',value:'0',unit:'个'
    },{
      area:'锦屏街道',name:'天然特用林壯龄竹珠数',value:'0',unit:'个'
    },{
      area:'锦屏街道',name:'天然特用林老龄竹珠数',value:'0',unit:'个'
    },{
      area:'锦屏街道',name:'天然用材林种植总面积',value:'134',unit:'亩'									
    },{			
      area:'锦屏街道',name:'天然用材林总珠数',value:'441',unit:'个'
    },{
      area:'锦屏街道',name:'天然用材林壯龄竹珠数',value:'420',unit:'个'
    },{
      area:'锦屏街道',name:'天然用材林老龄竹珠数',value:'21',unit:'个'
    },{
      area:'岳林街道',name:'合计种植总面积',value:'815',unit:'亩'						
    },{
      area:'岳林街道',name:'合计总珠数',value:'87',unit:'个'			
    },{
      area:'岳林街道',name:'合计壯龄竹珠数',value:'191',unit:'个'
    },{
      area:'岳林街道',name:'合计老龄竹珠数',value:'152',unit:'个'
    },{
      area:'岳林街道',name:'合计防护林种植总面积',value:'87',unit:'亩'						
    },{
      area:'岳林街道',name:'合计防护林总珠数',value:'191',unit:'个'
    },{
      area:'岳林街道',name:'合计防护林壯龄竹珠数',value:'152',unit:'个'
    },{
      area:'岳林街道',name:'合计防护林老龄竹珠数',value:'39',unit:'个'			
    },{
      area:'岳林街道',name:'合计特用林种植总面积',value:'0',unit:'亩'			
    },{
      area:'岳林街道',name:'合计特用林总珠数',value:'0',unit:'个'
    },{
      area:'岳林街道',name:'合计特用林壯龄竹珠数',value:'0',unit:'个'
    },{
      area:'岳林街道',name:'合计特用林老龄竹珠数',value:'0',unit:'个'						
    },{
      area:'岳林街道',name:'合计用材林种植总面积',value:'728',unit:'亩'								
    },{			
      area:'岳林街道',name:'合计用材林总珠数',value:'1949',unit:'个'
    },{
      area:'岳林街道',name:'合计用材林壯龄竹珠数',value:'1150',unit:'个'
    },{
      area:'岳林街道',name:'合计用材林老龄竹珠数',value:'800',unit:'个'			
    },{
      area:'岳林街道',name:'人工种植总面积',value:'815',unit:'亩'			
    },{
      area:'岳林街道',name:'人工总珠数',value:'2140',unit:'个'		
    },{
      area:'岳林街道',name:'人工壯龄竹珠数',value:'1301',unit:'个'
    },{
      area:'岳林街道',name:'人工老龄竹珠数',value:'839',unit:'个'
    },{
      area:'岳林街道',name:'人工防护林种植总面积',value:'87',unit:'亩'						
    },{
      area:'岳林街道',name:'人工防护林总珠数',value:'191',unit:'个'
    },{
      area:'岳林街道',name:'人工防护林壯龄竹珠数',value:'152',unit:'个'
    },{
      area:'岳林街道',name:'人工防护林老龄竹珠数',value:'39',unit:'个'
    },{
      area:'岳林街道',name:'人工特用林种植总面积',value:'0',unit:'亩'						
    },{			
      area:'岳林街道',name:'人工特用林总珠数',value:'0',unit:'个'
    },{
      area:'岳林街道',name:'人工特用林壯龄竹珠数',value:'0',unit:'个'
    },{
      area:'岳林街道',name:'人工特用林老龄竹珠数',value:'0',unit:'个'
    },{
      area:'岳林街道',name:'人工用材林种植总面积',value:'728',unit:'亩'						
    },{			
      area:'岳林街道',name:'人工用材林总珠数',value:'1949',unit:'个'
    },{
      area:'岳林街道',name:'人工用材林壯龄竹珠数',value:'1150',unit:'个'
    },{
      area:'岳林街道',name:'人工用材林老龄竹珠数',value:'800',unit:'个'			
    },{			
      area:'岳林街道',name:'天然种植总面积',value:'0',unit:'亩'
    },{
      area:'岳林街道',name:'天然总珠数',value:'0',unit:'个'		
    },{
      area:'岳林街道',name:'天然壯龄竹珠数',value:'0',unit:'个'
    },{
      area:'岳林街道',name:'天然老龄竹珠数',value:'0',unit:'个'
    },{
      area:'岳林街道',name:'天然防护林种植总面积',value:'0',unit:'亩'						
    },{
      area:'岳林街道',name:'天然防护林总珠数',value:'0',unit:'个'
    },{
      area:'岳林街道',name:'天然防护林壯龄竹珠数',value:'0',unit:'个'
    },{
      area:'岳林街道',name:'天然防护林老龄竹珠数',value:'0',unit:'个'
    },{
      area:'岳林街道',name:'天然特用林种植总面积',value:'0',unit:'亩'						
    },{			
      area:'岳林街道',name:'天然特用林总珠数',value:'0',unit:'个'
    },{
      area:'岳林街道',name:'天然特用林壯龄竹珠数',value:'0',unit:'个'
    },{
      area:'岳林街道',name:'天然特用林老龄竹珠数',value:'0',unit:'个'
    },{
      area:'岳林街道',name:'天然用材林种植总面积',value:'0',unit:'亩'									
    },{			
      area:'岳林街道',name:'天然用材林总珠数',value:'0',unit:'个'
    },{
      area:'岳林街道',name:'天然用材林壯龄竹珠数',value:'0',unit:'个'
    },{
      area:'岳林街道',name:'天然用材林老龄竹珠数',value:'0',unit:'个'
    },{
      area:'江口街道',name:'合计种植总面积',value:'330',unit:'亩'						
    },{
      area:'江口街道',name:'合计总珠数',value:'777',unit:'个'			
    },{
      area:'江口街道',name:'合计壯龄竹珠数',value:'587',unit:'个'
    },{
      area:'江口街道',name:'合计老龄竹珠数',value:'190',unit:'个'			
    },{
      area:'江口街道',name:'合计防护林种植总面积',value:'100',unit:'亩'						
    },{
      area:'江口街道',name:'合计防护林总珠数',value:'240',unit:'个'
    },{
      area:'江口街道',name:'合计防护林壯龄竹珠数',value:'163',unit:'个'
    },{
      area:'江口街道',name:'合计防护林老龄竹珠数',value:'76',unit:'个'			
    },{
      area:'江口街道',name:'合计特用林种植总面积',value:'0',unit:'亩'			
    },{
      area:'江口街道',name:'合计特用林总珠数',value:'0',unit:'个'
    },{
      area:'江口街道',name:'合计特用林壯龄竹珠数',value:'0',unit:'个'
    },{
      area:'江口街道',name:'合计特用林老龄竹珠数',value:'0',unit:'个'						
    },{
      area:'江口街道',name:'合计用材林种植总面积',value:'230',unit:'亩'								
    },{			
      area:'江口街道',name:'合计用材林总珠数',value:'538',unit:'个'
    },{
      area:'江口街道',name:'合计用材林壯龄竹珠数',value:'424',unit:'个'
    },{
      area:'江口街道',name:'合计用材林老龄竹珠数',value:'114',unit:'个'			
    },{
      area:'江口街道',name:'人工种植总面积',value:'330',unit:'亩'						
    },{
      area:'江口街道',name:'人工总珠数',value:'777',unit:'个'		
    },{
      area:'江口街道',name:'人工壯龄竹珠数',value:'587',unit:'个'
    },{
      area:'江口街道',name:'人工老龄竹珠数',value:'190',unit:'个'			
    },{
      area:'江口街道',name:'人工防护林种植总面积',value:'100',unit:'亩'						
    },{
      area:'江口街道',name:'人工防护林总珠数',value:'240',unit:'个'
    },{
      area:'江口街道',name:'人工防护林壯龄竹珠数',value:'163',unit:'个'
    },{
      area:'江口街道',name:'人工防护林老龄竹珠数',value:'76',unit:'个'
    },{
      area:'江口街道',name:'人工特用林种植总面积',value:'0',unit:'亩'						
    },{			
      area:'江口街道',name:'人工特用林总珠数',value:'0',unit:'个'
    },{
      area:'江口街道',name:'人工特用林壯龄竹珠数',value:'0',unit:'个'
    },{
      area:'江口街道',name:'人工特用林老龄竹珠数',value:'0',unit:'个'
    },{
      area:'江口街道',name:'人工用材林种植总面积',value:'230',unit:'亩'				
    },{			
      area:'江口街道',name:'人工用材林总珠数',value:'538',unit:'个'
    },{
      area:'江口街道',name:'人工用材林壯龄竹珠数',value:'424',unit:'个'
    },{
      area:'江口街道',name:'人工用材林老龄竹珠数',value:'114',unit:'个'			
    },{			
      area:'江口街道',name:'天然种植总面积',value:'0',unit:'亩'
    },{
      area:'江口街道',name:'天然总珠数',value:'0',unit:'个'		
    },{
      area:'江口街道',name:'天然壯龄竹珠数',value:'0',unit:'个'
    },{
      area:'江口街道',name:'天然老龄竹珠数',value:'0',unit:'个'
    },{
      area:'江口街道',name:'天然防护林种植总面积',value:'0',unit:'亩'						
    },{
      area:'江口街道',name:'天然防护林总珠数',value:'0',unit:'个'
    },{
      area:'江口街道',name:'天然防护林壯龄竹珠数',value:'0',unit:'个'
    },{
      area:'江口街道',name:'天然防护林老龄竹珠数',value:'0',unit:'个'
    },{
      area:'江口街道',name:'天然特用林种植总面积',value:'0',unit:'亩'						
    },{			
      area:'江口街道',name:'天然特用林总珠数',value:'0',unit:'个'
    },{
      area:'江口街道',name:'天然特用林壯龄竹珠数',value:'0',unit:'个'
    },{
      area:'江口街道',name:'天然特用林老龄竹珠数',value:'0',unit:'个'
    },{
      area:'江口街道',name:'天然用材林种植总面积',value:'0',unit:'亩'									
    },{			
      area:'江口街道',name:'天然用材林总珠数',value:'0',unit:'个'
    },{
      area:'江口街道',name:'天然用材林壯龄竹珠数',value:'0',unit:'个'
    },{
      area:'江口街道',name:'天然用材林老龄竹珠数',value:'0',unit:'个'
    },{
      area:'萧王庙街道',name:'合计种植总面积',value:'29428',unit:'亩'									
    },{
      area:'萧王庙街道',name:'合计总珠数',value:'84319',unit:'个'			
    },{
      area:'萧王庙街道',name:'合计壯龄竹珠数',value:'23068',unit:'个'
    },{
      area:'萧王庙街道',name:'合计老龄竹珠数',value:'61251',unit:'个'						
    },{
      area:'萧王庙街道',name:'合计防护林种植总面积',value:'121',unit:'亩'						
    },{
      area:'萧王庙街道',name:'合计防护林总珠数',value:'310',unit:'个'
    },{
      area:'萧王庙街道',name:'合计防护林壯龄竹珠数',value:'158',unit:'个'
    },{
      area:'萧王庙街道',name:'合计防护林老龄竹珠数',value:'153',unit:'个'			
    },{
      area:'萧王庙街道',name:'合计特用林种植总面积',value:'0',unit:'亩'			
    },{
      area:'萧王庙街道',name:'合计特用林总珠数',value:'0',unit:'个'
    },{
      area:'萧王庙街道',name:'合计特用林壯龄竹珠数',value:'0',unit:'个'
    },{
      area:'萧王庙街道',name:'合计特用林老龄竹珠数',value:'0',unit:'个'						
    },{
      area:'萧王庙街道',name:'合计用材林种植总面积',value:'29307',unit:'亩'							
    },{			
      area:'萧王庙街道',name:'合计用材林总珠数',value:'84009',unit:'个'
    },{
      area:'萧王庙街道',name:'合计用材林壯龄竹珠数',value:'22910',unit:'个'
    },{
      area:'萧王庙街道',name:'合计用材林老龄竹珠数',value:'61099',unit:'个'			
    },{
      area:'萧王庙街道',name:'人工种植总面积',value:'26182',unit:'亩'							
    },{
      area:'萧王庙街道',name:'人工总珠数',value:'75243',unit:'个'		
    },{
      area:'萧王庙街道',name:'人工壯龄竹珠数',value:'14085',unit:'个'
    },{
      area:'萧王庙街道',name:'人工老龄竹珠数',value:'61158',unit:'个'						
    },{
      area:'萧王庙街道',name:'人工防护林种植总面积',value:'55',unit:'亩'						
    },{
      area:'萧王庙街道',name:'人工防护林总珠数',value:'138',unit:'个'
    },{
      area:'萧王庙街道',name:'人工防护林壯龄竹珠数',value:'78',unit:'个'
    },{
      area:'萧王庙街道',name:'人工防护林老龄竹珠数',value:'60',unit:'个'
    },{
      area:'萧王庙街道',name:'人工特用林种植总面积',value:'0',unit:'亩'						
    },{			
      area:'萧王庙街道',name:'人工特用林总珠数',value:'0',unit:'个'
    },{
      area:'萧王庙街道',name:'人工特用林壯龄竹珠数',value:'0',unit:'个'
    },{
      area:'萧王庙街道',name:'人工特用林老龄竹珠数',value:'0',unit:'个'
    },{
      area:'萧王庙街道',name:'人工用材林种植总面积',value:'26127',unit:'亩'				
    },{			
      area:'萧王庙街道',name:'人工用材林总珠数',value:'75105',unit:'个'
    },{
      area:'萧王庙街道',name:'人工用材林壯龄竹珠数',value:'14007',unit:'个'
    },{
      area:'萧王庙街道',name:'人工用材林老龄竹珠数',value:'61099',unit:'个'			
    },{			
      area:'萧王庙街道',name:'天然种植总面积',value:'3246',unit:'亩'			
    },{
      area:'萧王庙街道',name:'天然总珠数',value:'9076',unit:'个'		
    },{
      area:'萧王庙街道',name:'天然壯龄竹珠数',value:'8983',unit:'个'
    },{
      area:'萧王庙街道',name:'天然老龄竹珠数',value:'93',unit:'个'
    },{
      area:'萧王庙街道',name:'天然防护林种植总面积',value:'66',unit:'亩'							
    },{
      area:'萧王庙街道',name:'天然防护林总珠数',value:'173',unit:'个'
    },{
      area:'萧王庙街道',name:'天然防护林壯龄竹珠数',value:'80',unit:'个'
    },{
      area:'萧王庙街道',name:'天然防护林老龄竹珠数',value:'93',unit:'个'
    },{
      area:'萧王庙街道',name:'天然特用林种植总面积',value:'0',unit:'亩'						
    },{			
      area:'萧王庙街道',name:'天然特用林总珠数',value:'0',unit:'个'
    },{
      area:'萧王庙街道',name:'天然特用林壯龄竹珠数',value:'0',unit:'个'
    },{
      area:'萧王庙街道',name:'天然特用林老龄竹珠数',value:'0',unit:'个'
    },{
      area:'萧王庙街道',name:'天然用材林种植总面积',value:'3180',unit:'亩'											
    },{			
      area:'萧王庙街道',name:'天然用材林总珠数',value:'8903',unit:'个'
    },{
      area:'萧王庙街道',name:'天然用材林壯龄竹珠数',value:'8903',unit:'个'
    },{
      area:'萧王庙街道',name:'天然用材林老龄竹珠数',value:'0',unit:'个'
    },{
      area:'西坞街道',name:'合计种植总面积',value:'5223',unit:'亩'								
    },{
      area:'西坞街道',name:'合计总珠数',value:'17769',unit:'个'			
    },{
      area:'西坞街道',name:'合计壯龄竹珠数',value:'15797',unit:'个'
    },{
      area:'西坞街道',name:'合计老龄竹珠数',value:'1972',unit:'个'						
    },{
      area:'西坞街道',name:'合计防护林种植总面积',value:'3779',unit:'亩'								
    },{
      area:'西坞街道',name:'合计防护林总珠数',value:'12946',unit:'个'
    },{
      area:'西坞街道',name:'合计防护林壯龄竹珠数',value:'11935',unit:'个'
    },{
      area:'西坞街道',name:'合计防护林老龄竹珠数',value:'1012',unit:'个'			
    },{
      area:'西坞街道',name:'合计特用林种植总面积',value:'69',unit:'亩'						
    },{
      area:'西坞街道',name:'合计特用林总珠数',value:'237',unit:'个'
    },{
      area:'西坞街道',name:'合计特用林壯龄竹珠数',value:'115',unit:'个'
    },{
      area:'西坞街道',name:'合计特用林老龄竹珠数',value:'123',unit:'个'						
    },{
      area:'西坞街道',name:'合计用材林种植总面积',value:'1375',unit:'亩'							
    },{			
      area:'西坞街道',name:'合计用材林总珠数',value:'4585',unit:'个'
    },{
      area:'西坞街道',name:'合计用材林壯龄竹珠数',value:'3748',unit:'个'
    },{
      area:'西坞街道',name:'合计用材林老龄竹珠数',value:'838',unit:'个'			
    },{
      area:'西坞街道',name:'人工种植总面积',value:'5179',unit:'亩'								
    },{
      area:'西坞街道',name:'人工总珠数',value:'17621',unit:'个'		
    },{
      area:'西坞街道',name:'人工壯龄竹珠数',value:'15649',unit:'个'
    },{
      area:'西坞街道',name:'人工老龄竹珠数',value:'1972',unit:'个'						
    },{
      area:'西坞街道',name:'人工防护林种植总面积',value:'3763',unit:'亩'									
    },{
      area:'西坞街道',name:'人工防护林总珠数',value:'12897',unit:'个'
    },{
      area:'西坞街道',name:'人工防护林壯龄竹珠数',value:'11885',unit:'个'
    },{
      area:'西坞街道',name:'人工防护林老龄竹珠数',value:'1012',unit:'个'			
    },{
      area:'西坞街道',name:'人工特用林种植总面积',value:'41',unit:'亩'						
    },{			
      area:'西坞街道',name:'人工特用林总珠数',value:'139',unit:'个'
    },{
      area:'西坞街道',name:'人工特用林壯龄竹珠数',value:'17',unit:'个'
    },{
      area:'西坞街道',name:'人工特用林老龄竹珠数',value:'123',unit:'个'
    },{
      area:'西坞街道',name:'人工用材林种植总面积',value:'1375',unit:'亩'						
    },{			
      area:'西坞街道',name:'人工用材林总珠数',value:'4585',unit:'个'
    },{
      area:'西坞街道',name:'人工用材林壯龄竹珠数',value:'3748',unit:'个'
    },{
      area:'西坞街道',name:'人工用材林老龄竹珠数',value:'838',unit:'个'			
    },{			
      area:'西坞街道',name:'天然种植总面积',value:'44',unit:'亩'						
    },{
      area:'西坞街道',name:'天然总珠数',value:'148',unit:'个'		
    },{
      area:'西坞街道',name:'天然壯龄竹珠数',value:'148',unit:'个'
    },{
      area:'西坞街道',name:'天然老龄竹珠数',value:'0',unit:'个'
    },{
      area:'西坞街道',name:'天然防护林种植总面积',value:'16',unit:'亩'								
    },{
      area:'西坞街道',name:'天然防护林总珠数',value:'50',unit:'个'
    },{
      area:'西坞街道',name:'天然防护林壯龄竹珠数',value:'50',unit:'个'
    },{
      area:'西坞街道',name:'天然防护林老龄竹珠数',value:'0',unit:'个'
    },{
      area:'西坞街道',name:'天然特用林种植总面积',value:'28',unit:'亩'							
    },{			
      area:'西坞街道',name:'天然特用林总珠数',value:'98',unit:'个'
    },{
      area:'西坞街道',name:'天然特用林壯龄竹珠数',value:'98',unit:'个'
    },{
      area:'西坞街道',name:'天然特用林老龄竹珠数',value:'0',unit:'个'
    },{
      area:'西坞街道',name:'天然用材林种植总面积',value:'0',unit:'亩'											
    },{			
      area:'西坞街道',name:'天然用材林总珠数',value:'0',unit:'个'
    },{
      area:'西坞街道',name:'天然用材林壯龄竹珠数',value:'0',unit:'个'
    },{
      area:'西坞街道',name:'天然用材林老龄竹珠数',value:'0',unit:'个'
    },{
      area:'溪口镇',name:'合计种植总面积',value:'64304',unit:'亩'											
    },{
      area:'溪口镇',name:'合计总珠数',value:'165522',unit:'个'			
    },{
      area:'溪口镇',name:'合计壯龄竹珠数',value:'82562',unit:'个'
    },{
      area:'溪口镇',name:'合计老龄竹珠数',value:'82960',unit:'个'						
    },{
      area:'溪口镇',name:'合计防护林种植总面积',value:'28605',unit:'亩'							
    },{
      area:'溪口镇',name:'合计防护林总珠数',value:'72390',unit:'个'
    },{
      area:'溪口镇',name:'合计防护林壯龄竹珠数',value:'44553',unit:'个'
    },{
      area:'溪口镇',name:'合计防护林老龄竹珠数',value:'27837',unit:'个'			
    },{
      area:'溪口镇',name:'合计特用林种植总面积',value:'0',unit:'亩'						
    },{
      area:'溪口镇',name:'合计特用林总珠数',value:'0',unit:'个'
    },{
      area:'溪口镇',name:'合计特用林壯龄竹珠数',value:'0',unit:'个'
    },{
      area:'溪口镇',name:'合计特用林老龄竹珠数',value:'0',unit:'个'						
    },{
      area:'溪口镇',name:'合计用材林种植总面积',value:'35699',unit:'亩'					
    },{			
      area:'溪口镇',name:'合计用材林总珠数',value:'93132',unit:'个'
    },{
      area:'溪口镇',name:'合计用材林壯龄竹珠数',value:'38009',unit:'个'
    },{
      area:'溪口镇',name:'合计用材林老龄竹珠数',value:'55123',unit:'个'			
    },{
      area:'溪口镇',name:'人工种植总面积',value:'64011',unit:'亩'									
    },{
      area:'溪口镇',name:'人工总珠数',value:'164778',unit:'个'		
    },{
      area:'溪口镇',name:'人工壯龄竹珠数',value:'82306',unit:'个'
    },{
      area:'溪口镇',name:'人工老龄竹珠数',value:'82473',unit:'个'						
    },{
      area:'溪口镇',name:'人工防护林种植总面积',value:'28355',unit:'亩'					
    },{
      area:'溪口镇',name:'人工防护林总珠数',value:'71744',unit:'个'
    },{
      area:'溪口镇',name:'人工防护林壯龄竹珠数',value:'44338',unit:'个'
    },{
      area:'溪口镇',name:'人工防护林老龄竹珠数',value:'27406',unit:'个'			
    },{
      area:'溪口镇',name:'人工特用林种植总面积',value:'0',unit:'亩'						
    },{			
      area:'溪口镇',name:'人工特用林总珠数',value:'0',unit:'个'
    },{
      area:'溪口镇',name:'人工特用林壯龄竹珠数',value:'0',unit:'个'
    },{
      area:'溪口镇',name:'人工特用林老龄竹珠数',value:'0',unit:'个'
    },{
      area:'溪口镇',name:'人工用材林种植总面积',value:'35656',unit:'亩'									
    },{			
      area:'溪口镇',name:'人工用材林总珠数',value:'93035',unit:'个'
    },{
      area:'溪口镇',name:'人工用材林壯龄竹珠数',value:'37968',unit:'个'
    },{
      area:'溪口镇',name:'人工用材林老龄竹珠数',value:'55067',unit:'个'			
    },{			
      area:'溪口镇',name:'天然种植总面积',value:'293',unit:'亩'								
    },{
      area:'溪口镇',name:'天然总珠数',value:'744',unit:'个'		
    },{
      area:'溪口镇',name:'天然壯龄竹珠数',value:'256',unit:'个'
    },{
      area:'溪口镇',name:'天然老龄竹珠数',value:'487',unit:'个'
    },{
      area:'溪口镇',name:'天然防护林种植总面积',value:'250',unit:'亩'								
    },{
      area:'溪口镇',name:'天然防护林总珠数',value:'646',unit:'个'
    },{
      area:'溪口镇',name:'天然防护林壯龄竹珠数',value:'215',unit:'个'
    },{
      area:'溪口镇',name:'天然防护林老龄竹珠数',value:'431',unit:'个'
    },{
      area:'溪口镇',name:'天然特用林种植总面积',value:'0',unit:'亩'							
    },{			
      area:'溪口镇',name:'天然特用林总珠数',value:'0',unit:'个'
    },{
      area:'溪口镇',name:'天然特用林壯龄竹珠数',value:'0',unit:'个'
    },{
      area:'溪口镇',name:'天然特用林老龄竹珠数',value:'0',unit:'个'
    },{
      area:'溪口镇',name:'天然用材林种植总面积',value:'43',unit:'亩'								
    },{			
      area:'溪口镇',name:'天然用材林总珠数',value:'98',unit:'个'
    },{
      area:'溪口镇',name:'天然用材林壯龄竹珠数',value:'41',unit:'个'
    },{
      area:'溪口镇',name:'天然用材林老龄竹珠数',value:'57',unit:'个'
    }]
  },
  {
    type: '杂竹',    bambooData: [{
      area:'奉化区',name:'合计种植总面积',value:'41667',unit:'亩'
    },{
      area:'奉化区',name:'合计旱竹面积',value:'40703',unit:'亩'
    },{
      area:'奉化区',name:'合计珠数',value:'828361.64',unit:'个'
    },{
      area:'奉化区',name:'合计防护林种植总面积',value:'6376',unit:'亩'			
    },{
      area:'奉化区',name:'合计防护林旱竹面积',value:'6176',unit:'亩'
    },{
      area:'奉化区',name:'合计防护林珠数',value:'114789.98',unit:'个'
    },{
      area:'奉化区',name:'合计特用林种植总面积',value:'188',unit:'亩'			
    },{			
      area:'奉化区',name:'合计特用林旱竹面积',value:'26',unit:'亩'
    },{
      area:'奉化区',name:'合计特用林珠数',value:'4607.5',unit:'个'
    },{
      area:'奉化区',name:'合计用材林种植总面积',value:'35103',unit:'亩'						
    },{			
      area:'奉化区',name:'合计用材林旱竹面积',value:'34501',unit:'亩'
    },{
      area:'奉化区',name:'合计用材林珠数',value:'708964.26',unit:'个'
    },{
      area:'奉化区',name:'人工种植总面积',value:'40830',unit:'亩'
    },{
      area:'奉化区',name:'人工总旱竹面积',value:'40388',unit:'亩'		
    },{
      area:'奉化区',name:'人工总珠数',value:'813204.4',unit:'个'
    },{
      area:'奉化区',name:'人工防护林种植总面积',value:'6109',unit:'亩'						
    },{
      area:'奉化区',name:'人工防护林旱竹面积',value:'5997',unit:'亩'
    },{
      area:'奉化区',name:'人工防护林珠数',value:'110321.8',unit:'个'
    },{
      area:'奉化区',name:'人工特用林种植总面积',value:'26',unit:'亩'						
    },{			
      area:'奉化区',name:'人工特用林旱竹面积',value:'26',unit:'亩'
    },{
      area:'奉化区',name:'人工特用林珠数',value:'719.5',unit:'个'
    },{
      area:'奉化区',name:'人工用材林种植总面积',value:'34695',unit:'亩'						
    },{			
      area:'奉化区',name:'人工用材林旱竹面积',value:'34365',unit:'亩'
    },{
      area:'奉化区',name:'人工用材林珠数',value:'702162.6',unit:'个'
    },{			
      area:'奉化区',name:'天然种植总面积',value:'837',unit:'亩'
    },{
      area:'奉化区',name:'天然总旱竹面积',value:'315',unit:'亩'		
    },{
      area:'奉化区',name:'天然总珠数',value:'15157.84',unit:'个'
    },{
      area:'奉化区',name:'天然防护林种植总面积',value:'267',unit:'亩'						
    },{
      area:'奉化区',name:'天然防护林旱竹面积',value:'179',unit:'亩'
    },{
      area:'奉化区',name:'天然防护林珠数',value:'4469.18',unit:'个'
    },{
      area:'奉化区',name:'天然特用林种植总面积',value:'162',unit:'亩'						
    },{			
      area:'奉化区',name:'天然特用林旱竹面积',value:'0',unit:'亩'
    },{
      area:'奉化区',name:'天然特用林珠数',value:'3888',unit:'个'
    },{
      area:'奉化区',name:'天然用材林种植总面积',value:'408',unit:'亩'						
    },{			
      area:'奉化区',name:'天然用材林旱竹面积',value:'136',unit:'亩'
    },{
      area:'奉化区',name:'天然用材林珠数',value:'6800.66',unit:'个'
    }]
  }
]